<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllEvenements($recherche = null, $langue = null, $categorie = null, $admin = false, $limit = null)
    {
        $qb = $this->createQueryBuilder('e');

        /**
         * recherche via le titre
         */
        if(!empty($recherche)){
            $qb->andWhere('e.titre LIKE :recherche')
                ->setParameter('recherche', '%'.$recherche.'%');
        }

        /**
         * recherche via la langue
         */
        if(!empty($langue)){
            $qb->andWhere('e.langue = :langue')
               ->setParameter('langue', $langue);
        }

        /**
         * recherche via la catégorie
         */
        if(!empty($categorie)){
            $qb->andWhere('e.categorie = :categorie')
                ->setParameter('categorie', $categorie);
        }

        if($admin) $qb->orderBy('e.id', 'DESC');
        else{
            $qb->andWhere('e.isActive =  :isActive')
               ->setParameter('isActive', true)
               ->andWhere('e.avant LIKE :avant')
               ->setParameter('avant', false)
               ->andWhere('e.fin >=  :fin')
               ->setParameter('fin', new \DateTime('now'))
               ->orderBy('e.debut', 'ASC');
        }

        if(!empty($limit)){
            $qb->setMaxResults($limit);
        }

        return $query = $qb->getQuery()->getResult();
    }

    public function getAllEvenementsCalendrier()
    {
        $qb = $this->createQueryBuilder('e')
                   ->andWhere('e.isActive =  :isActive')
                   ->setParameter('isActive', true)
                   ->andWhere('e.fin >=  :fin')
                   ->setParameter('fin', new \DateTime('now'))
                   ->orderBy('e.debut', 'ASC');

        return $query = $qb->getQuery()->getResult();
    }

    public function getAvantEvenement()
    {
        $qb = $this->createQueryBuilder('e')
                   ->andWhere('e.isActive =  :isActive')
                   ->setParameter('isActive', true)
                   ->andWhere('e.avant LIKE :avant')
                   ->setParameter('avant', true)
                   ->andWhere('e.fin >=  :fin')
                   ->setParameter('fin', new \DateTime('now'))
                   ->setMaxResults(1)
                   ->orderBy('e.debut', 'ASC');

        return $query = $qb->getQuery()->getOneOrNullResult();
    }

    public function getCurrentEvenement($id)
    {
        $qb = $this->createQueryBuilder('e')
                   ->andWhere('e.isActive =  :isActive')
                   ->setParameter('isActive', true)
                   ->andWhere('e.fin >=  :fin')
                   ->setParameter('fin', new \DateTime('now'))
                   ->andWhere('e.id = :id')
                   ->setParameter('id', $id);

        return $query = $qb->getQuery()->getOneOrNullResult();

    }

}
